name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        ruby_version: [ruby-head, '3.1', '3.0', '2.7']
        rails_version: ['edge', '7.0']

        include:
          - ruby_version: '3.1'
            rails_version: '6.1'
          - ruby_version: '3.0'
            rails_version: '6.1'
          - ruby_version: '2.7'
            rails_version: '6.1'
          - ruby_version: '2.6'
            rails_version: '6.1'

          - ruby_version: '3.0'
            rails_version: '6.0'
          - ruby_version: '2.7'
            rails_version: '6.0'
          - ruby_version: '2.6'
            rails_version: '6.0'

          - ruby_version: '2.7'
            rails_version: '5.2'
          - ruby_version: '2.6'
            rails_version: '5.2'

          - ruby_version: '2.5'
            rails_version: '5.1'

          - ruby_version: '2.5'
            rails_version: '5.0'

          - ruby_version: '2.5'
            rails_version: '4.2'

    runs-on: ubuntu-20.04

    env:
      RAILS_VERSION: ${{ matrix.rails_version }}

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
          rubygems: ${{ matrix.ruby_version < '2.6' && 'default' || 'latest' }}
          bundler: ${{ matrix.rails_version == '4.2' && '1' || 'latest' }}
        continue-on-error: ${{ (matrix.ruby_version == 'ruby-head') || (matrix.allow_failures == 'true') }}

      - run: bundle exec rake
        continue-on-error: ${{ (matrix.ruby_version == 'ruby-head') || contains(matrix.rails_version, 'edge') || (matrix.allow_failures == 'true') }}
